# Generated by Django 5.0.4 on 2024-04-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_applyjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Declined', 'Declined'), ('Accepted', 'Accepted')], max_length=20),
        ),
    ]
